apiVersion: v1
kind: Service
metadata:
  name: accommodation-2306275600-fe-service
spec:
  selector:
    app: accommodation-2306275600-fe
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80